include:
  - local: /ci/lint/docker.yaml
  - local: /ci/dotnet_core.yaml
  - local: /ci/package/dotnet_core_ecs.yaml
  - local: /ci/inspection/security_docker.yaml
  - local: /ci/publish/docker_apps.yaml
  - local: /cd/deploy_aws.yaml

variables:
  DEPLOY_DOCKER: "true"

stages:
  - lint                  # jobs: docker_best_practice (branches e tags)
  - build                 # jobs: build (branches e tags)
  - test                  # jobs: unit_test (branches e tags)
  - package               # jobs: package (branches e tags)
  - inspection            # jobs: quality_check (branches), quality (tags), security_check (branches), security (tags)
  - publish               # jobs: publish (tags)
  - deploy_dev            # jobs: deploy_dev (master)
  - deploy_hom            # jobs: deploy_hom (tags)
  - governance            # jobs: create_jira_ticket (tags)
  - deploy_prd            # jobs: deploy_prd (tags)
