stages:
  - deploy_dev

variables:
  K8S_YAML: ""

.deploy_dev:
  stage: deploy_dev
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/deploy_kubernetes:snapshot
  variables:
    KUBECTL_COMMAND: "apply"
  script:
    - echo GoK8s
  environment:
    name: dev
  dependencies: []
  cache: {}
  tags:
    - golden
  only:
    - master
    - branches

deploy_dev:
  except:
    variables:
      - $DISABLE_DEPLOY_DEV
  extends: .deploy_dev
