stages:
  - deploy_hom

.deploy_hom:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/deploy_puppet:latest
  stage: deploy_hom
  allow_failure: false
  script:
    - echo "#GoChapter"
  only:
    - tags
  environment:
    name: hom
  dependencies: []
  cache: {}
  tags:
    - golden
  when: manual

deploy_hom:
  except:
    variables:
      - $DISABLE_DEPLOY_HOM
  extends: .deploy_hom
