stages:
  - infra_dev
  

.dev_plan:
  extends: .plan
  stage: infra_plan
  only:
    - branches
  environment:
    name: dev
    # action: prepare

dev_plan:
  extends: .dev_plan
  except:
    variables:
      - $DISABLE_INFRA_DEV
      - $TERRAFORM_MODULE

.dev_apply:
  extends: .apply
  stage: infra_dev
  only:
    - master
  environment:
    name: dev

dev_apply:
  extends: .dev_apply
  except:
    variables:
      - $DISABLE_INFRA_DEV
      - $TERRAFORM_MODULE
  dependencies: ["dev_plan"]
