stages:
  - inspection

variables:
  SONAR_OPTS: "-Dproject.settings=sonar-project.properties"

.sonar_template:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/sonar_inspection:latest
  stage: inspection
  allow_failure: false
  script:
    - sonar-scanner
  tags:
    - golden
  except:
    variables:
      - $DISABLE_INSPECTION_QUALITY
      - $DISABLE_INSPECTION

quality_check:
  extends: .sonar_template
  allow_failure: true
  only:
    - branches

quality:
  extends: .sonar_template
  only:
    - tags



