openapi: 3.0.3
info:
  title: {{NAME_PROJECT}}
  version: '1.0'
  description: A simple {{NAME_PROJECT}} REST service
  contact:
    email: alexandre.bitencourt@zup.com.br
servers:
  - url: 'http://localhost:3000'
paths:
  /{{NAME_PROJECT|to_kebab}}:
    post:
      summary: A {{NAME_PROJECT}} using POST http method and JSON body
      operationId: post-hello
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
              examples:
                example-1:
                  value:
                    greeting: Hello John!
      description: Receive a name in a JSON request body and respond with a greeting message for the name informed
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HelloRequest'
            examples:
              example-1:
                value:
                  name: John
    get:
      summary: Hello service using query param
      operationId: get-hello
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
              examples:
                example-1:
                  value:
                    greeting: Hello John!
      description: Receive a name in a query parameter and respond with a greeting message for the name informed
      parameters:
        - schema:
            type: string
          in: query
          name: name
          required: true
          description: Name to use in greeting message
  /{{NAME_PROJECT|to_kebab}}/{name}:
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
    get:
      summary: Hello service using path param
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
              examples:
                example-1:
                  value:
                    greeting: Hello John!
      operationId: get-hello-name
      description: Receive a name in a path parameter and respond with a greeting message for the name informed
components:
  schemas:
    HelloRequest:
      title: HelloRequest
      type: object
      properties:
        name:
          type: string
      required:
        - name
    HelloResponse:
      title: HelloResponse
      type: object
      properties:
        greeting:
          type: string
      required:
        - greeting