stages:
  - deploy_prd

.deploy_prd:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/deploy_puppet:latest
  stage: deploy_prd
  allow_failure: false
  script:
    - echo "#GoChapter"
  only:
    - tags
  environment:
    name: prd
  dependencies: []
  cache: {}
  tags:
    - golden
  when: manual

deploy_prd:
  except:
    variables:
      - $DISABLE_DEPLOY_PRD
  extends: .deploy_prd
