stages:
  - package

variables:
  appdynamics: "false"
  DOCKER_BUILD_PARAMS: "."
  IMAGE_NAME_SUFIX: "" # Utilizado quando o repositorio gera mais de uma imagem docker.
  IMAGE_NAME: ${CI_PROJECT_NAME}${IMAGE_NAME_SUFIX}

.package_docker:
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:cli
  stage: package
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-base.depdes.artifactory.prod.cloud.ihf"]
  script:
    - docker build -t ${IMAGE_NAME} --build-arg APPDYNAMICS=$appdynamics $DOCKER_BUILD_PARAMS
    - docker save -o ${IMAGE_NAME}.tar ${IMAGE_NAME}
  artifacts:
    expire_in: 1 day
    paths:
      - ${IMAGE_NAME}.tar

package:
  extends: .package_docker
  except:
    variables:
      - $DISABLE_PACKAGE
