variables:
  DOTNET_VERSION: "5.0"
  DOTNET_PROJECT_PATH: src/
  DOtNET_NUGET_PARAMS: ''

stages:
  - package

.package_nuget:
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/dotnet/sdk:$DOTNET_VERSION
  stage: package
  script:
    - cd $DOTNET_PROJECT_PATH
    - dotnet pack --output package $DOtNET_NUGET_PARAMS
  allow_failure: false
  artifacts:
    expire_in: 1 day
    paths:
      - $DOTNET_PROJECT_PATH/package
  tags:
    - ci

package_snapshot:
  extends: .package_nuget
  except:
    variables:
      - $DISABLE_PACKAGE
  only:
    - branches

package:
  extends: .package_nuget
  variables:
    DOtNET_NUGET_PARAMS: '-p:PackageVersion=${CI_COMMIT_TAG}'
  except:
    variables:
      - $DISABLE_PACKAGE
  only:
    - tags
