include:
  - local: /ci/package/docker_image.yaml

variables:
  DOTNET_VERSION: "3.1"
  DOTNET_PROJECT_PATH: "."
  DOTNET_PUBLISH_PARAMS: "-c Release -o release"
  IMAGE_NAME_SUFIX: "" # Utilizado quando o repositorio gera mais de uma imagem docker.
  IMAGE_NAME: ${CI_PROJECT_NAME}${IMAGE_NAME_SUFIX}

stages:
  - package

.package_dotnet:
  extends: .package_docker
  before_script:
    - docker run -i --rm -v $(pwd):/code -e DOTNET_PUBLISH_PARAMS="$DOTNET_PUBLISH_PARAMS" -e DOTNET_PROJECT_PATH="$DOTNET_PROJECT_PATH" itau-docker-base.depdes.artifactory.prod.cloud.ihf/dotnet/sdk:$DOTNET_VERSION sh -c 'cd /code/$DOTNET_PROJECT_PATH && dotnet publish $DOTNET_PUBLISH_PARAMS'
  artifacts:
    expire_in: 1 day
    paths:
      - ${IMAGE_NAME}.tar
      - src/**/release
      - ./**/release
  tags:
    - ci

package:
  extends: .package_dotnet
  except:
    variables:
      - $DISABLE_PACKAGE
