stages:
  - package

package:
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/tgz:1.0.0
  stage: package
  script:
    - 'ln -s ../${CI_PROJECT_NAME} ${CI_PROJECT_NAME}'
    - 'tar -czf ${CI_PROJECT_NAME}-${CI_PIPELINE_ID}.tgz ${CI_PROJECT_NAME}/* -C ${CI_PROJECT_NAME}
      --exclude ".git*" --exclude ./package/ --exclude *.sh
      --exclude sonar-project.properties --exclude coverage.xml
      --exclude ./tests --exclude ./test --exclude Dockerfile --exclude docker-compose.yml
      --exclude fortify_report.pdf --exclude *requirements*.txt --exclude .orange.yml'
  artifacts:
    expire_in: 1 day
    paths:
      - ${CI_PROJECT_NAME}-${CI_PIPELINE_ID}.tgz
  only:
    - tags
  except:
    variables:
      - $DISABLE_PACKAGE
  tags:
    - ci
