stages:
  - publish
  - publish_snapshot
  - publish_latest

variables:
  DOCKER_BUILD_ARGS: ""

# BRANCHES
.docker_golden_publish_snapshot:
  image: ${DOCKER_REGISTRY}/publish_docker:latest
  stage: publish
  allow_failure: false
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: itau-docker-golden.depdes.artifactory.prod.cloud.ihf
    VERSION_TAG: ""
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-golden.depdes.artifactory.prod.cloud.ihf"]
  script:
    - docker load -i $CI_PROJECT_NAME-$VERSION.tar
    - docker tag ${CI_PROJECT_NAME}:${VERSION} ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${VERSION_TAG:-snapshot}
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${VERSION_TAG:-snapshot}
  tags:
    - golden
  only:
    - branches
  except:
    variables:
      - $DISABLE_PUBLISH
  cache: {}

publish_snapshot:
  extends: .docker_golden_publish_snapshot

#
# TAGS
#
# version
.docker_golden_publish:
  image: ${DOCKER_REGISTRY}/publish_docker:latest
  stage: publish
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: itau-docker-golden.depdes.artifactory.prod.cloud.ihf
    VERSION_TAG: ""
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-golden.depdes.artifactory.prod.cloud.ihf"]
  script:
    - docker load -i $CI_PROJECT_NAME-$VERSION.tar
    - docker tag ${CI_PROJECT_NAME}:${VERSION} ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${VERSION_TAG:-${CI_COMMIT_TAG}}
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${VERSION_TAG:-${CI_COMMIT_TAG}}
  tags:
    - golden
  only:
    - tags
  except:
    variables:
      - $DISABLE_PUBLISH

publish:
  extends: .docker_golden_publish

# latest
.docker_golden_publish_latest:
  image: ${DOCKER_REGISTRY}/publish_docker:latest
  stage: publish_latest
  allow_failure: false
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: itau-docker-golden.depdes.artifactory.prod.cloud.ihf
    VERSION_TAG: ""
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-golden.depdes.artifactory.prod.cloud.ihf"]
  script:
    - docker pull ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    - docker tag ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${VERSION_TAG:-latest}
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${VERSION_TAG:-latest}
  tags:
    - golden
  only:
    - tags
  except:
    variables:
      - $DISABLE_PUBLISH
  when: manual
  cache: {}
  dependencies: []

publish_latest:
  extends: .docker_golden_publish_latest
