stages:
  - publish
  - publish_latest

.docker_publish:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/publish_docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: itau-docker-base.depdes.artifactory.prod.cloud.ihf
    PUBLISH_VERSION: ""
    PUBLISH_SUBPATH: ""
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-base.depdes.artifactory.prod.cloud.ihf"]
  stage: publish
  script:
    - CI_PROJECT_NAME_LOWER=`echo $CI_PROJECT_NAME | awk '{print tolower($0)}'`
    - if [[ -z "$PUBLISH_SUBPATH" ]]; then
        PUBLISH_PATH="${CI_PROJECT_NAME_LOWER}";
      else
        PUBLISH_PATH="${CI_PROJECT_NAME_LOWER}/${PUBLISH_SUBPATH}";
      fi
    - docker load -i ${CI_PROJECT_NAME}-${VERSION}.tar
    - docker tag ${CI_PROJECT_NAME}:${VERSION} ${DOCKER_REGISTRY}/${PUBLISH_PATH}:${PUBLISH_VERSION:-$VERSION}
    - docker push ${DOCKER_REGISTRY}/${PUBLISH_PATH}:${PUBLISH_VERSION:-$VERSION}
  tags:
    - golden
  only:
    - master
    - tags
  except:
    variables:
      - $DISABLE_PUBLISH
  cache: {}

variables:
  DISABLE_PUBLISH_LATEST: 1
  
publish_latest:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/publish_docker:latest
  stage: publish_latest
  allow_failure: false
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: itau-docker-base.depdes.artifactory.prod.cloud.ihf
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-base.depdes.artifactory.prod.cloud.ihf"]
  script:
    - docker pull ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${VERSION}
    - docker tag ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${VERSION} ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:latest
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:latest
  tags:
    - golden
  only:
    - master
    - tags
  except:
    variables:
      - $DISABLE_PUBLISH
      - $DISABLE_PUBLISH_LATEST
  when: manual
  cache: {}
  dependencies: []
