stages:
  - publish

variables:
  GRADLE_VERSION: "jdk11"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradlehome"

publish:
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/gradle:$GRADLE_VERSION
  stage: publish 
  script:
    - echo "As variavéis utilizadas neste comando são geradas automaticamente pela imagem de gradle."
    - cp "/home/docker/.gradle/gradle.properties" "$GRADLE_USER_HOME/"
    - ./gradlew publish --info
  only:
    - master
    - tags
  allow_failure: false
  artifacts:
    expire_in: 1 day
    paths:
      - ./build
      - gradle.properties
  cache:
    key: build
    paths:
      - .gradle
      - ./build/classes
      - .gradlehome/wrapper
      - .gradlehome/caches/modules*
  except:
    variables:
      - $DISABLE_PUBLISH
  tags:
    - ci
