variables:
  PYTHON_VERSION: 3.8.2

stages:
  - publish

.publish_python_lib:
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/python:$PYTHON_VERSION
  stage: publish
  script:
    - python3 setup.py sdist upload -r local

  except:
    variables:
      - $DISABLE_PUBLISH
  tags:
    - ci

publish:
  extends: .publish_python_lib
  only:
    - tags

publish_snapshot:
  extends: .publish_python_lib
  only:
    - master
