stages:
  - deploy_dev

# TADICIONAL
.deploy_dev:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/deploy_aws:latest
  stage: deploy_dev
  script:
    - echo "#GoChapter"
  only:
    - master
  environment:
    name: dev
  cache: {}
  tags:
    - golden

deploy_dev:
  dependencies: []
  except:
    variables:
      - $DISABLE_DEPLOY_DEV
      - $DEPLOY_DOCKER
  extends: .deploy_dev

# ECS
.deploy_dev_ecs:
  extends: .deploy_dev
  only:
    refs:
      - master
    variables:
      - $DEPLOY_DOCKER
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-applications.depdes.artifactory.prod.cloud.ihf"]

deploy_dev_ecs:
  extends: .deploy_dev_ecs
  except:
    variables:
      - $DISABLE_DEPLOY_DEV
