stages:
  - deploy_hom

# TRACIONAL
.deploy_hom:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/deploy_aws:latest
  stage: deploy_hom
  allow_failure: false
  script:
    - echo "#GoChapter"
  only:
    - tags
  environment:
    name: hom
  dependencies: []
  cache: {}
  tags:
    - golden
  when: manual

deploy_hom:
  except:
    variables:
      - $DISABLE_DEPLOY_HOM
      - $DEPLOY_DOCKER
  extends: .deploy_hom

# ECS   
.deploy_hom_ecs:
  extends: .deploy_hom
  only:
    refs:
      - tags
    variables:
      - $DEPLOY_DOCKER
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-applications.depdes.artifactory.prod.cloud.ihf"]

deploy_hom_ecs:
  extends: .deploy_hom_ecs
  except:
    variables:
      - $DISABLE_DEPLOY_HOM
