stages:
  - deploy_prd

# TRADICIONAL
.deploy_prd:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/deploy_aws:latest
  stage: deploy_prd
  allow_failure: false
  script:
    - echo "#GoChapter"
  only:
    - tags
  environment:
    name: prd
  dependencies: []
  cache: {}
  tags:
    - golden
  when: manual

deploy_prd:
  except:
    variables:
      - $DISABLE_DEPLOY_PRD
      - $DEPLOY_DOCKER
  extends: .deploy_prd

# ECS
.deploy_prd_ecs:
  extends: .deploy_prd
  only:
    refs:
      - tags
    variables:
      - $DEPLOY_DOCKER
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-applications.depdes.artifactory.prod.cloud.ihf"]

deploy_prd_ecs:
  extends: .deploy_prd_ecs
  except:
    variables:
      - $DISABLE_DEPLOY_PRD
