stages:
  - publish

variables:
  DOCKER_REGISTRY: itau-docker-applications.depdes.artifactory.prod.cloud.ihf
  IMAGE_NAME_SUFIX: "" # Utilizado quando o repositorio gera mais de uma imagem docker.
  IMAGE_NAME: ${CI_PROJECT_NAME}${IMAGE_NAME_SUFIX}

.docker_publish:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/publish_docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-applications.depdes.artifactory.prod.cloud.ihf"]
  stage: publish
  script:
    # Define IMAGE_NAME
    - docker load -i ${IMAGE_NAME}.tar
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${CI_COMMIT_TAG}
  tags:
    - golden
  only:
    - tags
  cache: {}

publish:
  extends: .docker_publish
  except:
    variables:
      - $DISABLE_PUBLISH

publish_snapshot:
  image: itau-docker-golden.depdes.artifactory.prod.cloud.ihf/publish_docker:latest
  stage: publish
  allow_failure: false
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_REGISTRY: itau-docker-applications.depdes.artifactory.prod.cloud.ihf
  services:
    - alias: docker
      name: itau-docker-base.depdes.artifactory.prod.cloud.ihf/docker:dind
      command: ["--insecure-registry=itau-docker-applications.depdes.artifactory.prod.cloud.ihf"]
  script:
    - docker load -i ${IMAGE_NAME}.tar
    - docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}:snapshot
    - docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:snapshot
  tags:
    - golden
  only:
    - master
    - branches
  except:
    variables:
      - $DISABLE_PUBLISH
  when: manual
  cache: {}