stages:
  - publish

pages:
  stage: publish
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/node:15.8.0
  script:
    - npm install swagger-ui-dist
    - npm install -g yamljs
    - cp -r node_modules/swagger-ui-dist/ public
    - sed -i 's/https:\/\/petstore.swagger.io\/v2\/swagger.json/.\/swagger.json/g' public/index.html 
    - sed -i -e '52d' public/index.html
    - test "$SWAGGER_EXTENSION" = "yaml" && find . -type f -regex ".*/\(dev\|hom\)/.*\.\(yml\|yaml\)" -exec yaml2json {} > public/swagger.json \;  || true
    - test "$SWAGGER_EXTENSION" = "json" && find . -type f -regex ".*/\(dev\|hom\)/.*\.\(json\)" -exec cp {} public/swagger.json \; || true
  artifacts:
    paths:
      -  public
  except:
    variables:
      - $DISABLE_PUBLISH_PAGES
  only:
    - tags
    - master
  tags:
    - ci
