include:
  - local: /ci/lint/docker.yaml
  - local: /ci/java_gradle.yaml
  - local: /ci/package/docker_image.yaml
  - local: /ci/inspection/security_docker.yaml
  - local: /ci/publish/docker_apps.yaml
  - local: /cd/deploy_aws.yaml

variables:
  DEPLOY_DOCKER: "true"

stages:
  - lint                  # jobs: docker_best_practice (branches e tags)
  - build                 # jobs: build (branches e tags)
  - test                  # jobs: unit_test (branches e tags)
  - package               # jobs: package (branches e tags)
  - inspection            # jobs: quality_check (branches), quality (tags), security_check (branches), security (tags)
  - publish               # jobs: publish (tags)
  - deploy_dev            # jobs: deploy_dev_ecs (master)
  - deploy_hom            # jobs: deploy_hom_ecs (tags)
  - governance            # jobs: create_jira_ticket (tags)
  - deploy_prd            # jobs: deploy_prd_ecs (tags)

# Depende do package para baixar a imagem docker.
deploy_dev:
  dependencies: 
    - package
