stages:
  - lint
  
variables:
  GRADLE_VERSION: "jdk11"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradlehome"
  
lint:
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/gradle:$GRADLE_VERSION
  stage: lint
  script:
    - ./gradlew detekt --info
  tags:
    - ci
  allow_failure: false
  artifacts:
    expire_in: 1 day
    paths:
      - ./build/libs
      - gradle.properties
  cache:
    key: build
    paths:
      - .gradle
      - ./build/classes
      - .gradlehome/wrapper
      - .gradlehome/caches/modules*
  except:
    variables:
      - $DISABLE_LINT
