stages:
  - lint

helm_tags:
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/helm:3.5.3
  stage: lint
  tags:
    - ci
  script:
    - if [[ "$(awk '/^name/ {print $2}' Chart.yaml)" != "${CI_PROJECT_NAME}" ]]; then echo "Project name must to be the same as chart name"; exit 1 ;fi
    - if [[ "$(awk '/^version/ {print $2}' Chart.yaml)" != "${CI_COMMIT_TAG}" ]]; then echo "Project version must to be the same as chart version"; exit 1 ;fi
    - helm lint .
  only:
    - tags

helm:
  image: itau-docker-base.depdes.artifactory.prod.cloud.ihf/helm:3.5.3
  stage: lint
  tags:
    - ci
  script:
    - if [[ "$(awk '/^name/ {print $2}' Chart.yaml)" != "${CI_PROJECT_NAME}" ]]; then echo "Project name must to be the same as chart name"; exit 1 ;fi
    - helm lint .
  only:
    - branches
    - master